path: ../data/dataset
train: train/images
val: val/images
test: test/images

nc: 6
names:
  0: sugar_beet
  1: verbascum_pulverulentum
  2: marrubium_vulgare
  3: isatis_tinctoria
  4: artemisia_ludoviciana
  5: carduus_nutans
