path: ../data
train:
  - dataset/train/images
  - roboflow_yeni/train/images
val:
  - dataset/val/images
  - roboflow_yeni/val/images
test:
  - dataset/test/images
  - roboflow_yeni/test/images

nc: 6
names:
  0: sugar_beet
  1: verbascum_pulverulentum
  2: marrubium_vulgare
  3: isatis_tinctoria
  4: artemisia_ludoviciana
  5: carduus_nutans
